export const MEMBER_TASK_LOADING = "MEMBER_TASK_LOADING";
export const MEMBER_TASK_SUCCESS = "MEMBER_TASK_SUCCESS";
export const MEMBER_TASK_FAIL = "MEMBER_TASK_FAIL";

export const FETCH_MEMBERS = "FETCH_MEMBERS";
